### PR TITLE
Plain JS -> Vanilla JS

### PR DESCRIPTION
**Pull request by MiniGod**

### CODE REVIEW

**Comment by AngeloG** [comment]
I'd argue that "plain JS" is a better wording than "vanilla JS" but that makes this thread kinda meta

**Comment by kevincarrogan** [comment]
I would tend to agree.

Vanilla JS to me implies sans-framework/library as opposed to non-transpiled.

**Comment by MiniGod** [comment]
Fair enough, @kevincarrogan.

I often hear Plain JS (or "normal js", or similar) being mistakenly used in place of Vanilla JS, so when I hear Plain JS I am not sure if they actually mean plain or vanilla.

**Comment by MiniGod** [comment]
In fact, shouldn't it then be CoffeeScript vs JavaScript?

**Comment by kevincarrogan** [comment]
Agreed and done.

**Pull request closed without merging**
